### ISSUE TITLE
How to run these binary files from the command line？

### ISSUE THREAD

**Issue by eee555** [thefinerminer/minesweeper-rawvf#2]
How to run these binary files from the command line, I have not used before. I'm on a windows 10 cmd.

I ran the code with VS2019 and it feels good.

I want to make a player in python. The method that comes to mind is to package the code as a dll. I would like to know if there is a better way?

Thank you very much.

**Comment by thefinerminer** [comment]
I've only uploaded the Linux binaries. If you compile the code on Windows in the cmd line type "parser_xyz.exe video.xyz>video.txt" to read the video. To add statistics type "parser_raw.exe video.txt>raw.txt".

Update - Windows binaries are now in the folder.
